services:
    contao_glossary.listener.generate_page:
        class: Oveleon\ContaoGlossaryBundle\EventListener\GeneratePageListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: generatePage }
        public: true

    contao_glossary.listener.insert_tags:
        class: Oveleon\ContaoGlossaryBundle\EventListener\InsertTagsListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }
        public: true

    contao_glossary.listener.breadcrumb:
        class: Oveleon\ContaoGlossaryBundle\EventListener\BreadcrumbListener
        tags:
            - { name: contao.hook, hook: generateBreadcrumb }
        public: true
